CREATE DATABASE IF NOT EXISTS staff;
USE staff;
SELECT DATABASE();

CREATE TABLE title (
  TITLE_ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE_NAME VARCHAR(25)
);

CREATE TABLE gender (
  GENDER_ID INT PRIMARY KEY AUTO_INCREMENT,
  GENDER_NAME VARCHAR(25)
);

CREATE TABLE usergroup (
  USERGROUP_ID INT PRIMARY KEY AUTO_INCREMENT,
  USERGROUP_CODE VARCHAR(50),
  USERGROUP_NAME VARCHAR(50),
  USERGROUP_REMARK VARCHAR(255),
  USERGROUP_URL VARCHAR(50)
);

CREATE TABLE user (
  USER_ID INT PRIMARY KEY AUTO_INCREMENT,
  USER_TITLE INT, 
  USER_FNAME VARCHAR(50),
  USER_LNAME VARCHAR(50),
  USER_GENDER INT,
  USER_EMAIL VARCHAR(50),
  USER_NAME VARCHAR(25),
  USER_PASSWD VARCHAR(25),
  USER_GROUPID INT,
  DISABLE INT,
  FOREIGN KEY (USER_TITLE) REFERENCES title(TITLE_ID),
  FOREIGN KEY (USER_GENDER) REFERENCES gender(GENDER_ID),
  FOREIGN KEY (USER_GROUPID) REFERENCES usergroup(USERGROUP_ID)
);

INSERT INTO title (TITLE_NAME) VALUES 
  ('Mr.'),
  ('Mrs.'),
  ('Ms.'),
  ('Dr.'),
  ('Prof.')
;

INSERT INTO gender (GENDER_NAME) VALUES 
  ('Male'),
  ('Female'),
  ('N/A')
;